"""
Trading signal data model
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass
class TradingSignal:
    """
    Represents a trading signal generated by AI analysis.
    """
    direction: str              # "CALL" or "PUT" or "NO_TRADE"
    confidence: int             # 0-100 percentage
    expiry: str                 # "35s", "1m", "2m", "5m", etc.
    entry_timing: str           # "now", "candle_close", "wait_pullback"
    asset: str                  # "EUR/USD (OTC)", "CAD/CHF (OTC)", etc.
    timeframes_analyzed: List[str] = field(default_factory=list)
    patterns_detected: List[str] = field(default_factory=list)
    reasoning: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Analysis metadata
    trend_higher_tf: str = ""   # "bullish", "bearish", "sideways"
    trend_lower_tf: str = ""
    key_levels: List[str] = field(default_factory=list)
    
    @property
    def is_valid(self) -> bool:
        """Check if this is a valid tradeable signal"""
        return (
            self.direction in ("CALL", "PUT") and
            self.confidence >= 60 and
            self.expiry != ""
        )
    
    @property
    def color(self) -> str:
        """Get color based on direction"""
        if self.direction == "CALL":
            return "#00d26a"  # Green
        elif self.direction == "PUT":
            return "#ff4757"  # Red
        else:
            return "#a0a0a0"  # Gray
    
    @property
    def emoji(self) -> str:
        """Get emoji based on direction"""
        if self.direction == "CALL":
            return "🟢"
        elif self.direction == "PUT":
            return "🔴"
        else:
            return "⚪"
    
    def to_display_text(self) -> str:
        """Format signal for display"""
        return f"{self.emoji} {self.direction} {self.asset}\n⏱️ Expiry: {self.expiry}\n📊 Confidence: {self.confidence}%"
    
    def to_short_text(self) -> str:
        """Short format for notifications"""
        return f"{self.direction} {self.asset} | {self.expiry} | {self.confidence}%"


@dataclass  
class AnalysisResult:
    """
    Complete result from AI analysis including signal and metadata.
    """
    signal: TradingSignal
    provider_used: str          # "gemini", "openai", "groq"
    analysis_time_ms: int       # Time taken for analysis
    images_analyzed: int        # Number of images sent
    raw_response: str = ""      # Raw AI response for debugging
    error: Optional[str] = None
    
    @property
    def success(self) -> bool:
        return self.error is None


def create_no_trade_signal(reason: str = "Analysis inconclusive") -> TradingSignal:
    """Create a NO_TRADE signal with the given reason"""
    return TradingSignal(
        direction="NO_TRADE",
        confidence=0,
        expiry="",
        entry_timing="wait",
        asset="Unknown",
        reasoning=reason
    )
